# CHANGE FILENAME : remove .example into projectname.yml

# CHANGE THIS
database:
  driver: ""
  max_conns: 100
  max_idle: 4
  read: "host=0.0.0.0 user=USER password=PASSWORD dbname=DB sslmode=disable"
  write: "host=0.0.0.0 user=USER password=PASSWORD dbname=DB sslmode=disable"
jwt:
  expires:
    access: 3600
    refresh: 604800
  secret:
    access: "" # random string
    refresh: "" # random string
PORT: 8080
